name: Deploy to EC2
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 43.204.130.37.nip.io
          username: ec2-user
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            # Pull latest changes and build
            cd /home/ec2-user/node-app
            git pull origin main
            npm install
            npm run build
            
            # Restart or Start Application via PM2
            if pm2 describe jira-ui > /dev/null 2>&1; then
              pm2 restart jira-ui
            else
              pm2 start npm --name "jira-ui" -- start
            fi
            pm2 save
